const menu = [
	{
		id: 1,
		title: 'butter croissant',
		category: 'breakfast',
		price: 4.99,
		img: './images/item-1.jpg',
		desc: `Veggies es bonus vobis, proinde vos postulo essum magis onion daikon amaranth tatsoi tomatillo melon azuki bean garlic. `,
	},
	{
		id: 2,
		title: 'pesto pasta salad',
		category: 'lunch',
		price: 12.99,
		img: './images/item-2.jpg',
		desc: `Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts greens dandelion wakame tomato.  `,
	},
	{
		id: 3,
		title: 'turkey & ham melt',
		category: 'lunch',
		price: 15.99,
		img: './images/item-3.jpg',
		desc: `Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water avocado napa cabbage asparagus.`,
	},
	{
		id: 4,
		title: 'colossal cobb',
		category: 'lunch',
		price: 13.99,
		img: './images/item-4.jpg',
		desc: `Celery potato scallion desert raisin horseradish spinach carrot soko. Lotus root water spinach fennel.  `,
	},
	{
		id: 5,
		title: 'mocha sundae',
		category: 'dessert',
		price: 7.99,
		img: './images/item-5.jpg',
		desc: `Brussels sprout coriander water chestnut gourd swiss chard wakame kohlrabi beetroot carrot watercress.`,
	},
	{
		id: 6,
		title: 'strawberry cream croissant',
		category: 'dessert',
		price: 9.99,
		img: './images/item-6.jpg',
		desc: `Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea. `,
	},
	{
		id: 7,
		title: 'cutest cupcakes',
		category: 'dessert',
		price: 7.99,
		img: './images/item-7.jpg',
		desc: `Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea. `,
	},
	{
		id: 8,
		title: 'tropical fruit plate',
		category: 'breakfast',
		price: 12.99,
		img: './images/item-8.png',
		desc: `Pea horseradish azuki bean lettuce avocado asparagus okra. Kohlrabi radish okra azuki bean corn fava bean mustard.  `,
	},
	{
		id: 9,
		title: 'egg sandwich',
		category: 'breakfast',
		price: 11.99,
		img: './images/item-9.jpg',
		desc: `Grape silver beet watercress potato tigernut corn groundnut. Chickweed okra pea winter.`,
	},
	{
		id: 10,
		title: 'caprese salad',
		category: 'lunch',
		price: 9.99,
		img: './images/item-10.jpg',
		desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
	},
	{
		id: 11,
		title: 'tiramisu',
		category: 'dessert',
		price: 11.99,
		img: './images/item-11.jpg',
		desc: `Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula.`,
	},
	{
		id: 12,
		title: 'portobello melt',
		category: 'lunch',
		price: 13.99,
		img: './images/item-12.jpg',
		desc: `Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean.`,
	},
]
export default menu
